# Generated by Django 4.2 on 2026-05-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employer_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
